### ISSUE TITLE
Include relevant remacs docs in our wiki

### ISSUE THREAD

**Issue by brotzeit** [emacs-ng/emacs-ng#223]
I can imagine that some stuff from the remacs wiki could be worth adding to our docs. I'm pretty sure we have to modify it, but stuff like https://github.com/remacs/remacs/wiki/Emacs-Types would certainly be helpful for new contributors.

**Comment by black7375** [comment]
It would be nice to include it in Emacs-ng Native Hacker's Handbook.

mkdocs.yml
```yml
- Native Hackers Handbook:
  - Architecture: architecture.md
  - Emacs Types: emacs-types.md
```
